# Generated by Django 5.0.1 on 2024-01-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('priority', models.CharField(max_length=255)),
                ('readiness', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_tracker.status')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_tracker.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_tracker.user'),
        ),
        migrations.CreateModel(
            name='User_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_tracker.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_tracker.user')),
            ],
        ),
    ]
