# Generated by Django 5.0.1 on 2024-01-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_task_user_status_task_task_id_user_user_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='user_task',
            name='task',
        ),
        migrations.RemoveField(
            model_name='user_task',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Status_Task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='User_Task',
        ),
    ]
