# Generated by Django 5.0.1 on 2024-01-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0004_task_status_task_user_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateField(),
        ),
    ]
