# Generated by Django 5.0.1 on 2024-01-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0005_alter_task_date_end_alter_task_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_task',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='user_task',
            old_name='worker',
            new_name='worker_id',
        ),
    ]
