# Generated by Django 5.0.1 on 2024-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0006_rename_task_user_task_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='Высокий', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='readiness',
            field=models.CharField(choices=[('100%', '100%'), ('75%', '75%'), ('50%', '50%'), ('25%', '25%'), ('0%', '0%')], default='0%', max_length=20),
        ),
    ]
